version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/ssl/certs:ro
    depends_on:
      - nextcloud
      - collabora

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    extra_hosts:
      - "collabora.local:192.168.1.12"

  # Collabora Online (CODE)
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    environment:
      - aliasgroup1=http://nextcloud.local
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:logging.level=debug
      - username=admin
      - password=admin
    extra_hosts:
      - "nextcloud.local:192.168.1.12"
